name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2

      - name: Setup libs
        run: |
          sudo apt-get install -y libsfml-dev
          sudo apt-get install clang-format
          sudo apt-get install xvfb  # Устанавливаем Xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99  # Устанавливаем переменную DISPLAY для использования Xvfb

      - name: Check codestyle
        run: |
          git ls-files *.{c,h} | xargs clang-format -i --verbose
          git diff --exit-code

      - name: Build application
        run: make
        
      - name: Build tests
        run: make tests
      
      - name: Run tests
        run: make run_tests
