name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup libs
        run: sudo apt-get install -y libsfml-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: make all

      - name: Run tests
        run: make run_tests
